//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Airplane()
        {
            this.Transport_Vehicle_Airplane = new HashSet<Transport_Vehicle_Airplane>();
        }
    
        public int airplaneId { get; set; }
        public string model { get; set; }
        public System.DateTime year { get; set; }
        public Nullable<int> pilotId { get; set; }
        public string airCompanyName { get; set; }
        public short capacity { get; set; }
        public short luggageCapacity { get; set; }
    
        public virtual Air_Company Air_Company { get; set; }
        public virtual Pilot Pilot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport_Vehicle_Airplane> Transport_Vehicle_Airplane { get; set; }
    }
}
