//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airports_Air_Company_Date
    {
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string AirportName { get; set; }
        public string CompanyName { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Air_Company Air_Company { get; set; }
    }
}
