//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counters
    {
        public string AirportName { get; set; }
        public byte counterNumber { get; set; }
        public Nullable<int> tellerId { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Teller Teller { get; set; }
    }
}
