//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDetails
    {
        public string startpointName { get; set; }
        public string destinationName { get; set; }
        public string model { get; set; }
        public System.TimeSpan boardingTime { get; set; }
        public System.TimeSpan departureTime { get; set; }
        public System.TimeSpan arrivalTime { get; set; }
        public string Pilot { get; set; }
    }
}
