//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listAllCarry
    {
        public int lugageId { get; set; }
        public double weight { get; set; }
        public string primaryColor { get; set; }
        public string secondaryColor { get; set; }
        public string airportName { get; set; }
        public string vehicleType { get; set; }
        public short year { get; set; }
    }
}
