//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luggage_Color
    {
        public Nullable<int> luggageId { get; set; }
        public string primaryColor { get; set; }
        public string secondaryColor { get; set; }
    
        public virtual Luggage Luggage { get; set; }
    }
}
