//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luggage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luggage()
        {
            this.Luggage_Color = new HashSet<Luggage_Color>();
        }
    
        public int lugageId { get; set; }
        public bool isSafe { get; set; }
        public bool isBaggageClaim { get; set; }
        public double weight { get; set; }
        public Nullable<int> transporterId { get; set; }
        public Nullable<int> securityId { get; set; }
        public Nullable<int> tellerId { get; set; }
        public Nullable<int> passangerId { get; set; }
    
        public virtual Security Security { get; set; }
        public virtual Transporter Transporter { get; set; }
        public virtual Teller Teller { get; set; }
        public virtual Passanger Passanger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luggage_Color> Luggage_Color { get; set; }
    }
}
