//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketId { get; set; }
        public short price { get; set; }
        public Nullable<int> tellerId { get; set; }
        public Nullable<int> flightId { get; set; }
        public Nullable<int> passangerId { get; set; }
    
        public virtual Teller Teller { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Passanger Passanger { get; set; }
    }
}
