//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_Vehicle_Airplane
    {
        public short luggageNumber { get; set; }
        public Nullable<int> airplaneId { get; set; }
        public Nullable<int> vehicleId { get; set; }
    
        public virtual Transport_Vehicle Transport_Vehicle { get; set; }
        public virtual Airplane Airplane { get; set; }
    }
}
