//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneLuggageBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transport_Vehicle()
        {
            this.Transport_Vehicle_Airplane = new HashSet<Transport_Vehicle_Airplane>();
        }
    
        public int vehicleId { get; set; }
        public string vehicleType { get; set; }
        public short year { get; set; }
        public Nullable<int> transporterId { get; set; }
        public string airportName { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Transporter Transporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport_Vehicle_Airplane> Transport_Vehicle_Airplane { get; set; }
    }
}
